Add support for Maximum QoS property on CONNACK
chkr1011/MQTTnet pull request #1021
Opened 2020-11-03 20:22 UTC by nayato

Adds support for Maximum QoS on CONNACK to comply with MQTT 5 specification.

2020-11-03 21:18 UTC, nayato commented
looking at CI run, failures do not appear to be related to this PR

2020-11-04 19:55 UTC, chkr1011 requested changes

2020-11-04 19:55 UTC, chkr1011 commented on Source/MQTTnet/Client/Connecting/MqttClientAuthenticateResult.cs
> +        public MqttQualityOfServiceLevel? MaximumQoS { get; set; }
In my opinion this should be not nullable. If the value is not present this should default to QoS 2 (From spec: Followed by a Byte with a value of either 0 or 1. It is a Protocol Error to include Maximum QoS more than once, or to have a value other than 0 or 1. If the Maximum QoS is absent, the Client uses a Maximum QoS of 2.). 

But not in this class. The conversion should be made in the data converter instead.

2020-11-04 19:55 UTC, chkr1011 commented on Source/MQTTnet/Formatter/V5/MqttV500DataConverter.cs
>                  TopicAliasMaximum = connAckPacket.Properties?.TopicAliasMaximum,
As stated above just add _?? MqttQualityOfServiceLevel.ExactlyOnce_

2020-11-04 19:55 UTC, chkr1011 commented on Source/MQTTnet/Formatter/V5/MqttV500PropertiesReader.cs
> +            return (MqttQualityOfServiceLevel)value;
Please add empty line below the }.

2020-11-06 18:59 UTC, chkr1011 approved these changes

2020-11-06 18:59 UTC, chkr1011 commented
Thank you for your contribution 👍

2020-11-06 19:00 UTC, merged

2021-01-04 18:35 UTC, chensiel commented
> From spec:
> Followed by a Byte with a value of either 0 or 1. It is a Protocol Error to include Maximum QoS more than once, or to have a value other than 0 or 1. If the Maximum QoS is absent, the Client uses a Maximum QoS of 2.

Ok thank you.
My broker send a wrong max qos value to me.