Added client documentation.
chkr1011/MQTTnet pull request #1055
Opened 2021-01-03 20:50 UTC by SeppPenner

First step of the documentation (This is only the client side).

MqttClientExtensions is still missing, I will do this soon (if needed).

@chkr1011 What do you think of this? I have tried to only add documentation where I thought it was useful. Nevertheless, I have no idea if I got everything (or too much) 😄

2021-01-05 18:49 UTC, chkr1011 requested changes
I added some comments (to the comments :smile:). 
For me there a 3 levels of comments currently: Useless, Useful, Very useful.
I only marked a couple of them to make clear what I would prefer. Please let me know what you think.

2021-01-05 18:49 UTC, chkr1011 commented on Source/MQTTnet.Extensions.ManagedClient/IManagedMqttClient.cs
> +        /// Gets a value indicating whether the client is started or not.
For me this comment has no valuable information because it is only the long version of the property name.

2021-01-05 18:49 UTC, chkr1011 commented on Source/MQTTnet/Client/Connecting/MqttClientAuthenticateResult.cs
> +        /// Hint: MQTT 5 feature only.
This is a good comment because it has an information (MQTT v5 only) which is not visible to the user.

2021-01-05 18:49 UTC, chkr1011 commented on Source/MQTTnet/Client/Connecting/MqttClientAuthenticateResult.cs
>          public uint? SessionExpiryInterval { get; set; }
This is also a not valuable comment but maybe adding what happens when the interval is set to null might be interesting or the unit which is seconds here.

2021-01-05 18:49 UTC, chkr1011 commented on Source/MQTTnet/Client/Connecting/MqttClientAuthenticateResult.cs
> +        /// In MQTT 5, user properties are basic UTF-8 string key-value pairs that you can append to almost every type of MQTT packet.
This is a very good comment because it gives the user several hints about the purpose and potential use cases.

2021-01-05 18:49 UTC, chkr1011 commented on Source/MQTTnet/Client/Options/IMqttClientOptions.cs
> +        /// </summary>
Very good comment.

2021-01-05 18:49 UTC, chkr1011 commented on Source/MQTTnet/Client/Options/IMqttClientOptions.cs
>          string ClientId { get; }
Good comment.

2021-01-05 18:49 UTC, chkr1011 commented on Source/MQTTnet/MqttTopicFilter.cs
> +        /// - At most once  (0): Message gets delivered no time, once or multiple times.
Very good comment.

2021-01-14 19:59 UTC, SeppPenner commented
Thank you for the update, I will check this and hopefully work on it tomorrow again :)

2021-01-15 19:44 UTC, SeppPenner commented
@chkr1011 Does this look sufficient to you?

2021-01-30 16:27 UTC, SeppPenner commented
@chkr1011 Did you have time to check this?

2021-01-30 21:38 UTC, chkr1011 commented
@SeppPenner I am fine with that. These comments have a real value for the user and I will also add them to new properties etc. in the future 👍 

Is there something to do or should I merge that state?

2021-01-30 22:05 UTC, SeppPenner commented
> 
> 
> @SeppPenner I am fine with that. These comments have a real value for the user and I will also add them to new properties etc. in the future 👍
> 
> Is there something to do or should I merge that state?

It can be merged :)

2021-01-31 10:33 UTC, merged

2021-02-03 08:09 UTC, juwens commented
@SeppPenner awsome. Thank you :)