Added option for how many subscriptions to send in a single call to t…
chkr1011/MQTTnet pull request #1209
Opened 2021-08-02 14:57 UTC by scottbrogden-iheartmedia

Added option for how many subscriptions to send in a single call to the server.  aws iotcore limits this to 8

2021-09-05 10:04 UTC, chkr1011 requested changes

2021-09-05 10:04 UTC, chkr1011 commented on Source/MQTTnet.Extensions.ManagedClient/IManagedMqttClientOptions.cs
> +        int? MaxSubcribeUnsubscribeMessagesAtOnce { get; }
Please start with a value of int.Max. This avoids null checks and boxing.

2021-09-05 10:04 UTC, chkr1011 commented on Source/MQTTnet.Extensions.ManagedClient/ManagedMqttClient.cs
> +                        //aws only allows 8 in a single message
Please move this comment to a real summary comment at property level. So all users can read that without accessing the source code.

2021-09-19 10:41 UTC, chkr1011 commented
I will merge this feature and do the changes on my own so that we have this feature available. @SeppPenner Do you want to add the notes to the wiki (only 8 topic filters are supported in AWS per subscription)? I will add this in code summary.

2021-09-19 10:41 UTC, merged

2021-09-19 12:14 UTC, SeppPenner commented
I have just added a small text to https://github.com/chkr1011/MQTTnet/wiki/Tips-and-Tricks#limits-for-multi-subscriptions-per-single-call. @chkr1011